### ISSUE TITLE
Deprecated selector in `railscasts-syntax/styles/base.less`

### ISSUE THREAD

**Issue by thibaudgg** [rpowelll/railscasts-syntax#3]
In `railscasts-syntax/styles/base.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor,
:host` => `atom-text-editor,atom-text-editor`

* `atom-text-editor .gutter,
:host .gutter` => `atom-text-editor .gutter,atom-text-editor .gutter`

* `atom-text-editor .gutter .line-number.cursor-line,
:host .gutter .line-number.cursor-line` => `atom-text-editor .gutter .line-number.cursor-line,atom-text-editor .gutter .line-number.cursor-line`

* `atom-text-editor .gutter .line-number.cursor-line-no-selection,
:host .gutter .line-number.cursor-line-no-selection` => `atom-text-editor .gutter .line-number.cursor-line-no-selection,atom-text-editor .gutter .line-number.cursor-line-no-selection`

* `atom-text-editor .wrap-guide,
:host .wrap-guide` => `atom-text-editor .wrap-guide,atom-text-editor .wrap-guide`

* `atom-text-editor .indent-guide,
:host .indent-guide` => `atom-text-editor .indent-guide,atom-text-editor .indent-guide`

* `atom-text-editor .invisible-character,
:host .invisible-character` => `atom-text-editor .invisible-character,atom-text-editor .invisible-character`

* `atom-text-editor .search-results .marker .region,
:host .search-results .marker .region` => `atom-text-editor .search-results .syntax--marker .region,atom-text-editor .search-results .syntax--marker .region`

* `atom-text-editor .search-results .marker.current-result .region,
:host .search-results .marker.current-result .region` => `atom-text-editor .search-results .syntax--marker.current-result .region,atom-text-editor .search-results .syntax--marker.current-result .region`

* `atom-text-editor.is-focused .cursor,
:host(.is-focused) .cursor` => `atom-text-editor.is-focused .cursor,atom-text-editor .cursor`

* `atom-text-editor.is-focused .selection .region,
:host(.is-focused) .selection .region` => `atom-text-editor.is-focused .selection .region,atom-text-editor .selection .region`

* `atom-text-editor.is-focused .line-number.cursor-line-no-selection,
atom-text-editor.is-focused .line.cursor-line,
:host(.is-focused) .line-number.cursor-line-no-selection,
:host(.is-focused) .line.cursor-line` => `atom-text-editor.is-focused .line-number.cursor-line-no-selection,
atom-text-editor.is-focused .line.cursor-line,atom-text-editor .line-number.cursor-line-no-selection,atom-text-editor .line.cursor-line`

* `.comment` => `.syntax--comment`

* `.keyword,
.storage` => `.syntax--keyword,
.syntax--storage`

* `.entity.name.function,
.keyword.other.name-of-parameter.objc` => `.syntax--entity.syntax--name.syntax--function,
.syntax--keyword.syntax--other.syntax--name-of-parameter.syntax--objc`

* `.entity.name` => `.syntax--entity.syntax--name`

* `.constant.numeric` => `.syntax--constant.syntax--numeric`

* `.variable.language,
.variable.other` => `.syntax--variable.syntax--language,
.syntax--variable.syntax--other`

* `.constant` => `.syntax--constant`

* `.variable.other.constant` => `.syntax--variable.syntax--other.syntax--constant`

* `.constant.language` => `.syntax--constant.syntax--language`

* `.string` => `.syntax--string`

* `.support.function` => `.syntax--support.syntax--function`

* `.support.type` => `.syntax--support.syntax--type`

* `.support.constant` => `.syntax--support.syntax--constant`

* `.meta.tag,
.declaration.tag,
.entity.name.tag,
.entity.other.attribute-name` => `.syntax--meta.syntax--tag,
.syntax--declaration.syntax--tag,
.syntax--entity.syntax--name.syntax--tag,
.syntax--entity.syntax--other.syntax--attribute-name`

* `.invalid` => `.syntax--invalid`

* `.constant.character.escaped,
.constant.character.escape,
.string .source,
.string .source.ruby` => `.syntax--constant.syntax--character.syntax--escaped,
.syntax--constant.syntax--character.syntax--escape,
.syntax--string .syntax--source,
.syntax--string .syntax--source.syntax--ruby`

* `.markup.inserted` => `.syntax--markup.syntax--inserted`

* `.markup.deleted` => `.syntax--markup.syntax--deleted`

* `.meta.diff.header,
.meta.separator.diff,
.meta.diff.index,
.meta.diff.range` => `.syntax--meta.syntax--diff.syntax--header,
.syntax--meta.syntax--separator.syntax--diff,
.syntax--meta.syntax--diff.syntax--index,
.syntax--meta.syntax--diff.syntax--range`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by rpowelll** [comment]
Resolved as of 0.4.1
